<?php

/**
 * Implements hook_theme().
 */
function site_location_time_theme($existing, $type, $theme, $path) {
    return [
        'site_location_time' => [
            'variables' => [
                'title' => 'Display Site Location and Time',
                'body' => NULL,
                'description' => NULL
            ],
            'template' => 'block--site-location-time',
        ]
    ];
}
